<?xml version="1.0"?>
<!-- Forklift -->
<robot name="forklift" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="body_mass" value="1" />
  <xacro:property name="lift1_mass" value="10" />
  <xacro:property name="lift2_mass" value="10" />
  <xacro:property name="wheelF_mass" value="10" />
  <xacro:property name="wheelB_mass" value="5" />

  <xacro:property name="wheelF_radius" value="0.33" />
  <xacro:property name="wheelF_width" value="0.01" />
  <xacro:property name="wheelB_radius" value="0.27" />
  <xacro:property name="wheelB_width" value="0.2" />

  <!-- Body dimensions -->
  <xacro:property name="length" value="2.65" /> 
  <xacro:property name="width" value="1.2" />
  <xacro:property name="height" value="1.9" />

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find forklift_description)/urdf/forklift.gazebo" />

  <xacro:macro name="cylinder_inertia" params="m r h">
            <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                      iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                      izz="${m*r*r/2}" /> 
  </xacro:macro>

  <xacro:macro name="cube_inertia" params="m w h d">
          <inertia
            ixx="${m / 12.0 * (h*h + d*d)}" ixy="0.0" ixz="0.0"
            iyy="${m / 12.0 * (d*d + w*w)}" iyz="0.0"
            izz="${m / 12.0 * (h*h + w*w)}"/>
  </xacro:macro>


  <!-- Forklift -->
  <link name="base_link">
    <collision>
      <origin xyz="-1 0 ${height/2 + 0.2}" rpy="0 0 0"/>
      <geometry>
	     <box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-0.89856 0 1.08726" rpy="0 0 ${PI/2}"/> <!-- -0.00203 -0.06282 1.08726-->
      <geometry>
	     <mesh filename="package://forklift_description/meshes/forklift_body.dae"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 1" rpy="0 0 0"/>
      <mass value="${body_mass}"/>
      <cube_inertia m="${lift1_mass}" w="1" h="1" d="1" />
    </inertial>
  </link>

  <!-- Import lift unit -->
  <xacro:include filename="$(find forklift_description)/urdf/forklift_lift.xacro" />

  <!-- Import front wheels -->
  <xacro:include filename="$(find forklift_description)/urdf/forklift_front_wheels.xacro" />

  <!-- Import back wheels -->
  <xacro:include filename="$(find forklift_description)/urdf/forklift_back_wheels.xacro" />

</robot>
